create table PROJECTS (
  ID INT NOT NULL AUTO_INCREMENT,
  TITLE varchar(100) not null,
  DESCRIPTION varchar(100) not null,
  DISPLAYCOLOR varchar(100) not null,
  USERID INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT USERID
  FOREIGN KEY (USERID)
  REFERENCES USERS (ID)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);
